#!/bin/bash

# Load the YAML file
yamlFile="scripts/pipeline-config.yml"
eval $(cat "$yamlFile" | sed 's/:[^:\/\/]/="/;s/$/"/')

# Access the variables
dockerImage="$dockerImage"
token="$token"
label="$label"

# Use the values in your script
echo "Running jenkin-build script..."
echo "Docker Image: $dockerImage"
echo "Token: $token"
echo "label: $label"

# Add your build logic here
# Customize the build process using these values
